spring.datasource.driver-class-name=${DATABASE_DRIVER:org.mariadb.jdbc.Driver}
spring.datasource.url=${DATABASE_URL:jdbc:mariadb://localhost:3306/dkont}
spring.datasource.username=${DATABASE_USERNAME:dkont}
spring.datasource.password=${DATABASE_PASSWORD:dkont}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
admin.security.skip-authorization-on-localhost=${SKIP_AUTHORIZATION_ON_LOCALHOST:false}
admin.local-panel.enabled=${ADMIN_LOCAL_PANEL_ENABLED:false}
admin.seed.username=${ADMIN_USERNAME:admin}
admin.seed.password=${ADMIN_PASSWORD:admin}
server.port=${SERVER_PORT:8082}